### ISSUE TITLE
Support for Multiple Backgrounds that are cycled through over time (like a slideshow)

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#10]

**Comment by IsaacMorris1980** [comment]
@colinkiama    you should see if this can be implemented for the background https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/rotatortile

**Comment by colinkiama** [comment]
This control seems great fit the short term but my plan was that the
background would change every few hours.

So, this control shouldn't be used.

**Comment by IsaacMorris1980** [comment]
Do you mean download image from webservice, files and folders on same computer, or files and folders on a network?

**Comment by colinkiama** [comment]
From files from the computer

**Comment by IsaacMorris1980** [comment]
@colinkiama 
does it need to run even when the app is not or only when the application is running?

if only when running then i would modify the loading settings function and attach to a thread timer and run it every 60 minutes or so

**Comment by colinkiama** [comment]
only when the app is running

**Comment by IsaacMorris1980** [comment]
do you want to allow users to say how long in between image changes?

**Comment by colinkiama** [comment]
nope

**Comment by IsaacMorris1980** [comment]
Do we want users to be able to delete images, or change image order

**Comment by colinkiama** [comment]
Yeah

**Comment by IsaacMorris1980** [comment]
@colinkiama   can you check my Cycle background branch and see what could be done better

**Comment by IsaacMorris1980** [comment]
@colinkiama  i have it where it cycles through  but i can not stop if from flickering when changing image  do you have any ideas?

**Comment by colinkiama** [comment]
Can you show me what the flickering looks like?

**Comment by IsaacMorris1980** [comment]
[Untitled.zip](https://github.com/colinkiama/UWP-App-Launcher/files/3087886/Untitled.zip)


Had to upload the video as a zip github does not support mp4

**Comment by colinkiama** [comment]
Oh. In that case, I recommend cycling through images using a flip view

**Comment by IsaacMorris1980** [comment]
even with the flipview i am still getting the flickering looking to add animation to see if i can animate smoothly when changing pictures

**Comment by IsaacMorris1980** [comment]
@colinkiama   even with animation i was unable to get smooth transistions, i changed flipview for rotatortile  and currently have the rotation delay set to 15 seconds to check image changing,  i get no flicker and it is smooth transistions  So far the only thing i do not have implemented for changing backgrounds is persistance  think i know how to do that currently working on it  if you would like to look at it i have it on cyclebackground branch

**Comment by colinkiama** [comment]
I've had a look. Yeah it works great.

**Comment by IsaacMorris1980** [comment]
@colinkiama   i am not sure if that branch had the persistance update to it or not  if not will upload soon

**Comment by IsaacMorris1980** [comment]
@colinkiama  that branch did have persistance is there anything else i should try.  I am looking to make the application more responsive

**Comment by colinkiama** [comment]
#8 would be awesome.

**Comment by IsaacMorris1980** [comment]
merge request #34   added feature
