### ISSUE TITLE
Not working on lumia 535

### ISSUE THREAD

**Issue by HunterAzar** [IsaacMorris1980/appLauncher#11]
This app kick me when it starting.

**Comment by colinkiama** [comment]
Sorry about that, I’m going to try my best to fix this problem!

But in order for me to do that, please tell me your name of device and the version of the OS you are running.

Sent from Mail for Windows 10

From: HunterAzar
Sent: 22 December 2017 05:46
To: colinkiama/UWP-App-Launcher
Cc: Subscribed
Subject: [colinkiama/UWP-App-Launcher] Not working on lumia 353 (#11)

This app kick me when it starting.

**Comment by HunterAzar** [comment]
Microsoft Lumia 535 DualSim
Windows 10 (1607)

**Comment by HunterAzar** [comment]
Sorry Lumia 535

**Comment by colinkiama** [comment]
So I've tested the app and I don't see anything wrong with its performance at startup. This used to be a big problem until the latest update which fixed the app crashing bug.

Since no-one else has mentioned that this has been a problem, I'm going to assume that this is just a special case.

One more question before I close the issue though. Are you on the latest version of the app?

**Comment by HunterAzar** [comment]
Yes i'm on ver 1.2.4.0

**Comment by colinkiama** [comment]
Very strange then...

**Comment by HunterAzar** [comment]
I cant install depends

**Comment by colinkiama** [comment]
Oh, how are you trying to install them and what is the error that you are seeing?

**Comment by HunterAzar** [comment]
![wp_ss_20171226_0002](https://user-images.githubusercontent.com/26726236/34354895-d4d4926e-ea31-11e7-9193-b4480d3817ed.png)

**Comment by HellLord77** [comment]
Same thing is happening in my Lumia 535 also, app closes automatically

**Comment by colinkiama** [comment]
Have you tried using the device portal to install the app?
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-mobile

**Comment by colinkiama** [comment]
No reply since 8 Feb so assumed that problem is fixed.
