### ISSUE TITLE
Redesign app

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#21]
Create mockup for the app and implement it.

**Comment by IsaacMorris1980** [comment]
what kind of redesign are you thinking of?

**Comment by colinkiama** [comment]
Polished Fluent Design

**Comment by colinkiama** [comment]
Imagine something like this but without the live tiles

**Comment by colinkiama** [comment]
Imagine something like this but without the live tiles 😍: https://www.behance.net/gallery/32664259/Windows-10-Mobile-Thinking-about-Details

**Comment by colinkiama** [comment]
Initial Settings page would look something like this: 
![Settings@1080p](https://user-images.githubusercontent.com/16501024/58372164-a6231780-7f11-11e9-96c4-958d0f50867d.png)

**Comment by colinkiama** [comment]
You can view the progress and make your own changes here too here: https://www.figma.com/file/ebvntZpuNhNerAaAdL5hQboe/UWP-App-Launcher-Fluent-Redesign?node-id=0%3A1

**Comment by IsaacMorris1980** [comment]
@colinkiama   would we need new pages or just expanded when clicking on titles?

**Comment by colinkiama** [comment]
What titles are you referring to?

>

**Comment by IsaacMorris1980** [comment]
@colinkiama   Are the position of elements absolute or fluid   

Each one i click on says position absolute

**Comment by colinkiama** [comment]
They are absolute.

**Comment by IsaacMorris1980** [comment]
@colinkiama   do you want the main pages to be resizable or just 360x 640?

**Comment by colinkiama** [comment]
Keep them as 360 X 640px. A separate design can be made for desktop sized screens

**Comment by IsaacMorris1980** [comment]
@colinkiama   I need a screen for the home page with more then one app displayed  to get spacing for apps similar to the picture used in settings(background) The one that shows how the app would look

We also need a page displaying about page

I am unable to find the code for the segoe mdl2 asset for background on settings preferences

**Comment by colinkiama** [comment]
Here, you can make it: https://www.figma.com/file/ebvntZpuNhNerAaAdL5hQboe/UWP-App-Launcher-Fluent-Redesign?node-id=0%3A1

**Comment by IsaacMorris1980** [comment]
Implementing a MVVM  framework, should make coding easier and more responsive and easier to maintain

**Comment by IsaacMorris1980** [comment]
Changing design of application
