### ISSUE TITLE
Change Minimum supported Windows to  version 16299?

### ISSUE THREAD

**Issue by IsaacMorris1980** [IsaacMorris1980/appLauncher#22]

**Comment by colinkiama** [comment]
Why?

**Comment by IsaacMorris1980** [comment]
closing was having issues when trying to run with anything below 16299

**Comment by IsaacMorris1980** [comment]
i think if the project moved to 15063  we could then make use of conditional xaml, I only open this as i was having an issue running with anything below 16299  but i found out what it was it will be fixed soon

Conditional xaml allows us to target different os versions  eg.  if paralaxview is only avaliable with api contract 5 and if the device does not it can display something else  this can also be done through code

**Comment by colinkiama** [comment]
We are still able to use parallax service instead with the Community Toolkit on Version 2.2.0
