### ISSUE TITLE
Crashes before showing Apps Screen on mobile

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#24]
I don't have a USB-C cable to debug the app on my phone. Could anyone else be able to figure out what's wrong? Otherwise, will just drop mobile support

**Comment by IsaacMorris1980** [comment]
@colinkiama  

 what version of the app ?
When did this start occuring?
What OS version on your device?
type of device etc.......

**Comment by IsaacMorris1980** [comment]
@colinkiama   were you able to determine the issue with mobile?

**Comment by colinkiama** [comment]
No.
