### ISSUE TITLE
New project leader required

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#25]
I have to admit, I've completely lost interest in the project. When I look back now, the only reason why I started making UWP apps was that I wanted to develop for Windows Phone. 

While this app is pretty redundant on PC, it does make a lot of sense for Windows 10 IoT. Because of this, the continuation of this project makes sense.

If you would like to take over, please let me know below so I can give you the privileges you need.

**Comment by valentinbreiz** [comment]
I hope someone talented will take over the project!

**Comment by ShadowEO** [comment]
If it's phones you are trying to contribute for, perhaps maybe retarget it for the WindowsOnArm project (similar to the scope of ADeltaX's MobileShell), which has developers attempting to update Windows phone devices using the full WOA desktop image?

**Comment by IsaacMorris1980** [comment]
@colinkiama  I would like to take it over

**Comment by colinkiama** [comment]
@IsaacMorris1980 okay. Will need you to delete your repository before I can transfer this one to you. If you have any changes you want to keep, set them as a pull request to this repo's "dev" branch.

**Comment by IsaacMorris1980** [comment]
@colinkiama   deleting repo now, i wanted to redo some of my changes so losing them is no issue

**Comment by colinkiama** [comment]
@IsaacMorris1980 I've sent a transfer request

**Comment by IsaacMorris1980** [comment]
transfer request accepted
