### ISSUE TITLE
Add ability to sort the order that apps are displayed

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#3]
### Ways that apps could be ordered:
* Alphabetical Order
* By Date,
* By Developer Name
* By Installed Date

**Comment by colinkiama** [comment]
Sorry, wrote that a while ago. Was referring to the properties: https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Package

InstallDate is Windows Phone only but InstalledDate supports all the platforms.

Edited the original comment so it's less confusing now.

**Comment by IsaacMorris1980** [comment]
would you like the critical bugs worked on before this one? If so which one would you like me to do?

**Comment by colinkiama** [comment]
Nope, it's fine.

**Comment by IsaacMorris1980** [comment]
Almost complete

**Comment by colinkiama** [comment]
Awesome! Really appreciate it! 😊

Will add a new release as soon as I can with your changes.
