### ISSUE TITLE
it not starting lumia 535

### ISSUE THREAD

**Issue by FreedomChuks** [IsaacMorris1980/appLauncher#5]
It will open show the splash screen and close back

**Comment by colinkiama** [comment]
What version of Windows 10 Mobile are you using?

**Comment by FreedomChuks** [comment]
Version 1703
Window 10 Mobile

**Comment by colinkiama** [comment]
Does it take a while before the app closes or does it close immediately?

**Comment by valentinbreiz** [comment]
Same issue on Lumia 640.
(also 1703)

**Comment by FreedomChuks** [comment]
same i dont know why , does i need intrope unlock?

**Comment by valentinbreiz** [comment]
I have Interop Unlocked my Lumia :/

**Comment by FreedomChuks** [comment]
pfft  am really tired of lumia

**Comment by colinkiama** [comment]
It doesn't need interop unlock however, someone suggesting increasing the page file size or making it dyanamic. They were using a Lumia 625 and it worked for them,

**Comment by colinkiama** [comment]
I've updated the app fixing a lot of bugs with getting the app list ready (now all windows "apps" are visible). Hopefully the launcher works on your phones now :) @gzodx  @valentinbreiz

**Comment by valentinbreiz** [comment]
That works now :)

**Comment by FreedomChuks** [comment]
i,ll try again please send me the link iv lost  it

**Comment by colinkiama** [comment]
https://github.com/colinkiama/UWP-App-Launcher/releases/tag/v1.2.0.0-beta

**Comment by FreedomChuks** [comment]
thanks

**Comment by colinkiama** [comment]
Issues are now resolved, app works well on all mobile devices!

**Comment by FreedomChuks** [comment]
Thanks for your hard work

On Sunday, November 26, 2017, Colin Kiama <notifications@github.com> wrote:
> Issues are now resolved, app works well on all mobile devices!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/pdEORtKyErxFvfb-Goa1Q7InIrfCWozjM_EPTXv7kFulw95FNcpuyvbmNURxLuNFWeqruHd_8qzztZ6PqUnG4Cm1i2HGWG1-BX4HMf8u1bWwFI2egIzS1FnWn-uCdfYKgL-r8qU81C7AaHznORH2XkS0AnFOKw=s0-d-e1-ft#https://github.com/notifications/beacon/Ad50PZg2WGbgqa__Sh18pqdTtISaEzgDks5s6cfTgaJpZM4PZvpI.gif>
