### ISSUE TITLE
(Recommended for first time contributers) Add support for more image formats

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#6]
You can do this by adding FilePicker filters for additional image format extensions. 
For example:  

`//Adds support for GIFs`
`picker.FileTypeFilter.Add(".gif");`

WARNING: **Don't** add video formats like .mp4 and .mkv

**Comment by brucremo** [comment]
Good evening @colinkiama! I would like to work on this feature if it is not taken yet, thanks in advance!

**Comment by colinkiama** [comment]
Oh, this is up to @IsaacMorris1980

**Comment by IsaacMorris1980** [comment]
@brucremo   it is ok with me i have changed to in progress and assigned to you

**Comment by IsaacMorris1980** [comment]
#39   adds more image support closing issue
