### ISSUE TITLE
Add ability to drag apps around to reorganise app list

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#7]
[It should behave similar to this video on iOS 10's App Icons](https://youtu.be/FnG1GHVNVy4?t=21s)

**Comment by IsaacMorris1980** [comment]
i would like to try this i think #9 might also be able to be done with this one

**Comment by colinkiama** [comment]
Sure, go ahead 😊 

Sent from my Windows 10 device

**Comment by IsaacMorris1980** [comment]
if i can get you a template in xaml how would you like it to be?

**Comment by colinkiama** [comment]
What do you mean by that?

Sent from my Windows 10 device

**Comment by IsaacMorris1980** [comment]
@colinkiama  i currently have it where you can re-arrange apps per page, but unable to move apps to another page.  it is also not persistant(each launch items back in same order) do we want this to be persisted?

**Comment by colinkiama** [comment]
Yes, please. 

By the way. I think this could be easier with pagination (sorry, I found out about this after I finished the UI): https://eren.ws/2013/10/29/implementing-pagination-in-windows-store-apps-using-flipview-boredom-challenge-day-25/

**Comment by IsaacMorris1980** [comment]
already looking into that, i  thank you for that because it does look promising. i am trying to bind the iobservable collection to the gridview so i can save the new order and redownload order on next start up.  it may require rewritting ui and code behind

**Comment by IsaacMorris1980** [comment]
Ui is updated just need to add back end and re-enable drag and drop of items and this will be good to go.  with luck and coding time i can have this ready by monday.

**Comment by IsaacMorris1980** [comment]
@colinkiama  sorry i have not had much time,  having issues with code behind may take longer then expected

**Comment by colinkiama** [comment]
Literally every project I've done ever haha. It's okay

**Comment by IsaacMorris1980** [comment]
@colinkiama   can you take a look at my branch changing order manually(that still is not implemented and see if you like the of the new flipview? i am still having issue re-implementing cortana will look into adding a blank page to begin with

**Comment by colinkiama** [comment]
Will do

**Comment by colinkiama** [comment]
I like this new dynamic flip view a lot! Great job! UI could use a bit of work but I can take care of that.

With Cortana, I can add that later, it's not really a higher priority thing.

I made some changes to how the the flip view dynamically updates: IsaacMorris1980#2
It makes the app a lot smoother but there's always a tiny delay when the flip view updates when changing the size of the window (which makes sense because it's a pretty intensive operation). Feel free to improve the code, I admit I rushed it due to the lack of time I have at the moment.

Good luck with getting the dragging and reorganising working

**Comment by IsaacMorris1980** [comment]
@colinkiama  when implementing drag and drop should i lay the foundation for #9 or just do it ?

**Comment by IsaacMorris1980** [comment]
@colinkiama your merge request is making more bugs, i get it to display appropriete tiles per page then touch the side and change it very little and now i have another row that appears with scrollbars.  not sure what is causing that looking into it further

**Comment by IsaacMorris1980** [comment]
i fixed the intial apps per screen(eg. calculated apps per screeen is 28)  , then when changing size even when using the same information as the initial apps per screen(eg. calculated apps per screeen is 28)  and it now displays 32 apps instead of 28  i have not found why

**Comment by colinkiama** [comment]
https://github.com/IsaacMorris1980/UWP-App-Launcher/blob/Changeordermanually/appLauncher/MainPage.xaml.cs

In MainPage_SizeChanged and Page_Loaded, the global variable for apps per screen is recalculated. That might be why I guess.

**Comment by IsaacMorris1980** [comment]
It was because both size changed and loaded were resetting items on the page, i commented out page loaded as size changed gets called every launch so it was adding apps to screen, in fixed  but now when resizing it is not recalculating correctly

**Comment by IsaacMorris1980** [comment]
@colinkiama   i have the dynamic flipview working for all sizes when the height gets too small there is a bigger gap between the buttons and rows of apps. I also have drag and drop working per page not between pages(that is the next thing i am working on along with persistance)

**Comment by IsaacMorris1980** [comment]
@colinkiama   do you know why when i run it now it pulls 150 apps when it used to pull only 44?  i have no idea why i have not changed packagemanager.getappsforuserwithpackagetypes() line of code

**Comment by colinkiama** [comment]
No idea. Maybe try uninstalling the app and running it again. 

Shouldn't be much of a problem anyway

**Comment by IsaacMorris1980** [comment]
weird when i undo my changes and run the application if finds 44, when i do my changes the same call finds 150 but i am not changing the call that gets the list of packages. and now none of the packages has a logo.  I honestly do not understand it. i am deleting all changes will thing of another way to serialize collection

**Comment by IsaacMorris1980** [comment]
@colinkiama   is there a default logo you would like used for apps that reply that they have no logo?

**Comment by colinkiama** [comment]
A solid accent colour I guess

**Comment by IsaacMorris1980** [comment]
@colinkiama   if figured out why i have missing icons they are light colors on light background when i changed the background color they displayed correctly

**Comment by IsaacMorris1980** [comment]
@colinkiama   i have everything but the drop ready as i am  having issues getting if another item is under the drop point do you have any ideas?

**Comment by colinkiama** [comment]
@IsaacMorris1980 I think you can combine this: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.drageventargs.getposition#Windows_UI_Xaml_DragEventArgs_GetPosition_Windows_UI_Xaml_UIElement_

with this: var a = ((FrameworkElement)e.OriginalSource).DataContext;

If 'a' is null or it isn't of the data type you are looking for then you can assume there's no item underneath.

**Comment by IsaacMorris1980** [comment]
@colinkiama   i have the drag and drop, persistance, now working on getting the pages to update without navigating away once that is done and i make the code better formatted and move some around i will submit PR  the latest code has not been pushed to github yet

**Comment by colinkiama** [comment]
Awesome work! Looking forward to the PR.

**Comment by colinkiama** [comment]
I recommend checking out https://github.com/IsaacMorris1980/UWP-App-Launcher/pull/5 

It's as snappy as the video I linked above now

**Comment by IsaacMorris1980** [comment]
Merge Request #34   added the ability to drag and drop apps around with persistance
