### ISSUE TITLE
Change Font Size of text in the launcher

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#8]

**Comment by IsaacMorris1980** [comment]
Bigger or smaller?

**Comment by IsaacMorris1980** [comment]
@colinkiama   do we want users to be able to change text size in settings?

**Comment by colinkiama** [comment]
it should be adjustable by the user.

**Comment by IsaacMorris1980** [comment]
i have it were it is adjustable by the user however i need help with how to figure out how many columns and rows with dynamically sized tiles since i thing you want the entire text to display.  

currently we use the size and height of the items we will need to recalculate based on dynamic size

**Comment by colinkiama** [comment]
Not going to change the size of the items. Just the text.

**Comment by IsaacMorris1980** [comment]
ok a PR should be comming soon
