### ISSUE TITLE
Add ability for user to create app folders First implementation New screen

### ISSUE THREAD

**Issue by colinkiama** [IsaacMorris1980/appLauncher#9]
[As shown as in this video here](https://youtu.be/6ecSig_redo?t=1m5s)

**Comment by IsaacMorris1980** [comment]
How will this be implemented will we need to create an abstract class that is used by app and folder?  or an interface?

**Comment by colinkiama** [comment]
An interface

**Comment by mediaexplorer74** [comment]
I discovered sweet old "folder player" sample by [colinkiama](https://github.com/colinkiama) . I hope it's userful for "Add ability for user to create app folders" issue solving:
https://github.com/colinkiama/FolderPlayerUWP/

**Comment by IsaacMorris1980** [comment]
Splitting implementation into 2  

First implementation will be  a new form to create the app folders

Second implementation will be able to do it from main screen

**Comment by IsaacMorris1980** [comment]
a crude version was released in v 2.3.1
